apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: cHJvZGJwYXNz   #pass is encoded from password in application.properties jdbc.password=vprodbpass
  rmq-pass: Z3Vlc3Q=      #pass is encoded from password in application.properties rabbitmq.password=guest
